# Project
version=0.7.0-BETA
group=de.minehackers.orchard
java_version=25

# Common
minecraft_version=26.3
mod_name=Orchard
mod_author=minehackers
mod_id=orchard
license=MIT
credits=
description=Custom tree generation using NBT structure templates. \nReplaces vanilla trees, huge fungi, and huge mushrooms with user-defined NBT files.
minecraft_version_range=[26.3, 26.4)
neo_form_version=26.3-1

# Fabric
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=26.3.0.22-beta
neoforge_loader_version_range=[4,)

# Libraries
snakeyaml_version=2.6
modmenu_version=21.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
